export default function SignalsPage() {
  return (
    <div className="min-h-screen pt-20 px-4" style={{ background: 'var(--bg-primary)' }}>
      <div className="max-w-7xl mx-auto">
        {/* Page Header */}
        <div className="mb-8 fade-in">
          <h1 className="text-3xl md:text-4xl font-extrabold mb-2"
            style={{ fontFamily: 'var(--font-display)' }}>
            Live Trading Signals
          </h1>
          <p style={{ color: 'var(--text-secondary)' }}>
            Real-time signals updated every 5 minutes. Powered by RSI, MACD, and volume analysis.
          </p>
        </div>

        {/* Filter Tabs */}
        <div className="flex gap-2 mb-8 flex-wrap">
          {['All', 'BUY', 'WATCH', 'WAIT'].map((filter) => (
            <button
              key={filter}
              className="px-4 py-2 rounded-lg text-sm font-semibold transition-all"
              style={{
                background: filter === 'All' ? 'var(--accent-blue-dim)' : 'var(--bg-card)',
                color: filter === 'All' ? 'var(--accent-blue)' : 'var(--text-secondary)',
                border: '1px solid var(--border-color)',
              }}
            >
              {filter}
            </button>
          ))}
        </div>

        {/* Signals Grid — Placeholder */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {[1, 2, 3, 4, 5, 6].map((i) => (
            <div key={i} className="card p-6">
              {/* Skeleton loading state */}
              <div className="flex items-center justify-between mb-4">
                <div className="skeleton w-24 h-6" />
                <div className="skeleton w-16 h-6" />
              </div>
              <div className="skeleton w-full h-4 mb-2" />
              <div className="skeleton w-3/4 h-4 mb-4" />
              <div className="flex items-center justify-between">
                <div className="skeleton w-20 h-8" />
                <div className="skeleton w-16 h-4" />
              </div>
            </div>
          ))}
        </div>

        {/* Info banner */}
        <div className="mt-8 p-4 rounded-xl text-center text-sm"
          style={{ background: 'var(--bg-card)', color: 'var(--text-secondary)', border: '1px solid var(--border-color)' }}>
          📊 Signals are generated by analyzing RSI, MACD, EMA crossovers, and volume patterns across 50+ coins.
          <br />
          This is not financial advice. Always do your own research.
        </div>
      </div>
    </div>
  );
}
